name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: Run tests
      run: sbt sbt-tasty-mima/scripted
    - name: Run scalafmt check
      run: sbt scalafmtCheck
